name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build without Tests
      run: mvn clean install -DskipTests

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: C:\Users\Lisan\Documents\Java PV2022\TpFinal-Grupo\dockerfile.yml
        push: true
        tags: lisandro1806/githubcd15-11:latest       
        build-args: |
          JAR_FILE=target/proyectoHIA.jar
