name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build without Tests
      run: mvn clean install -DskipTests

    - name: Build and Push Docker Image
      run: |
        docker buildx build \
          --build-arg JAR_FILE=proyectoHIA.jar \
          --file TpFinal-Grupo\dockerfile.yml \
          --tag lisandro1806/githubcd15-11:latest \
          --push .
